# -*- coding: utf-8 -*-
"""Pandas_groupby_Abdel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Ugp4Rzf8Ht_V6jDz0GQFCYVdMizRrOQ
"""

import pandas as pd    #pandas
import numpy as np    #numpy

import matplotlib.pyplot as plt  #para graficar matplotlib

df_Tunja=pd.read_csv("TUNJA.csv", encoding='latin-1')#leer de archivo en colab
df_Cartagena=pd.read_csv("CARTAGENA DE INDIAS.csv", encoding='latin-1')#leer de archivo en colab
df_Charala=pd.read_csv("CHARALÁ.csv", encoding='latin-1')#leer de archivo en colab
df_Ipiales=pd.read_csv("IPIALES.csv", encoding='latin-1')#leer de archivo en colab

print('-------------------------------------------------------------------')
df_all = pd.concat([df_Tunja, df_Cartagena, df_Charala, df_Ipiales])
print(df_all)
print('-------------------------------------------------------------------')
print('-------------------------------------------------------------------')
promedio_Tunja = df_all[df_all.Departamento == 'BOYACÁ']['Temperatura'].mean()
print('La temperatura promedio de tunja: ', promedio_Tunja)
promedio_Ipiales = df_all[df_all.Departamento == 'NARIÑO']['Temperatura'].mean()
print('La temperatura promedio de Ipiales: ', promedio_Ipiales)
promedio_Cartagena = df_all[df_all.Departamento == 'BOLÍVAR']['Temperatura'].mean()
print('La temperatura promedio de Cartagena: ', promedio_Cartagena)
promedio_Charala = df_all[df_all.Departamento == 'SANTANDER']['Temperatura'].mean()
print('La temperatura promedio de Charala: ', promedio_Charala)
print('-------------------------------------------------------------------')
print('-------------------------------------------------------------------')
max_Tunja = df_all[df_all.Departamento == 'BOYACÁ']['Temperatura'].max()
print('Valor maximo de tunja: ', max_Tunja)
print('-------------------------------------------------------------------')
print('-------------------------------------------------------------------')
tunja=df_all[df_all.Departamento == 'BOYACÁ']
print('Tunja tiene: ', len(tunja), ' Registos')
Ipiales=df_all[df_all.Departamento == 'NARIÑO']
print('Ipiales tiene: ', len(Ipiales), ' Registos')

print('-------------------------------------------------------------------')
print('-------------------------------------------------------------------')
tunja_1 = df_all[df_all.Departamento == 'BOYACÁ']['Temperatura']
plt.plot(tunja_1, label='Tunja')
Ipiales_1 = df_all[df_all.Departamento == 'NARIÑO']['Temperatura']
plt.plot(Ipiales_1, label='Ipiales')
Cartagena_1 = df_all[df_all.Departamento == 'BOLÍVAR']['Temperatura']
plt.plot(Cartagena_1, label='Cartagena')
Charala_1 = df_all[df_all.Departamento == 'SANTANDER']['Temperatura']
plt.plot(Charala_1, label='Charala')
plt.title("Temperaturas")
plt.ylabel("°C")
plt.xlabel("fechas")

plt.legend() #imprime labels

plt.show()
print('-------------------------------------------------------------------')
print('-------------------------------------------------------------------')
df_all.reset_index(drop=True, inplace=True)   #resetea el indix
print('-------------------------------------------------------------------')
print('-------------------------------------------------------------------')
for index in df_all.index:
    if df_all.loc[index,'Departamento']=='BOYACÁ':
        df_all.loc[index,'Región'] = 'Tunja'
    elif df_all.loc[index,'Departamento']=='NARIÑO':
        df_all.loc[index,'Región'] = 'Ipiales'
    elif df_all.loc[index,'Departamento']=='BOLÍVAR':
        df_all.loc[index,'Región'] = 'Cartagena'
    else:
        df_all.loc[index,'Región'] = 'Charala'


print('-------------------------------------------------------------------')
print('-------------------------------------------------------------------')

df_all.to_csv('all.csv') #exporta el dataframe